### ISSUE TITLE
'stk500() out of sync' while uploading code to vtx arduino

### ISSUE THREAD

**Issue by mjerrar** [UMD-AMAV/Terpcopter3.0#1]
Getting 'stk500() out of sync' error while uploading code to virtual transmitter arduino board through the arduino IDE.

**Comment by mjerrar** [comment]
Hold or press reset button on the arduino and release just before pressing the upload button on the IDE.
The cause of this problem might be the high baud rate continuous serial output of the arduino code previously uploaded and might be interfacing with IDE's upload command - which is also transported through serial, causing it to be lost in the serial traffic. The button press resets the arduino and creates a brief pause before the high baud rate data starts flowing allowing upload command to be heard. This technique might require multiple tries to match the timing.

**Comment by mjerrar** [comment]
Hold or press reset button on the arduino and release just before pressing the upload button on the IDE.
The cause of this problem might be the high baud rate continuous serial output of the arduino code previously uploaded and might be interfacing with IDE's upload command - which is also transported through serial, causing it to be lost in the serial traffic. The button press resets the arduino and creates a brief pause before the high baud rate data starts flowing allowing upload command to be heard. This technique might require multiple tries to match the timing.

**Comment by imoss15** [comment]
You need to select ATmega328P (old bootloader) while trying the above solution ^^
