### ISSUE TITLE
xterm: Cant't execvp matlab: No such file or directory 

### ISSUE THREAD

**Issue by krawal19** [UMD-AMAV/Terpcopter3.0#3]
master GUI opens xterm window with error xterm: Cant't execvp matlab: No such file or directory

**Comment by saimouli** [comment]
can you provide more details? A photo of your workspace and exact error and line number would help to debug. If you have already solved the issue, please post how you debugged and close the issue

**Comment by arturwolek** [comment]
This sounds like xterm does not have matlab in it's path. It may not be sourcing the .bashrc file. See this post:
https://unix.stackexchange.com/questions/483826/when-i-start-xterm-my-bashrc-doesnt-get-sourced

Also, can you clarify what in MATLAB is creating an xterm window and the purpose?

**Comment by mjerrar** [comment]
You had to change current Matlab folder to `amav/Tercopter3.0/matlab` to match the execution command with the location of scripts - xterm excepts them to be in a particular directory from where its launched. This is no longer required as this command has been added to run automatically when running the Master Launcher GUI.
